Repository Neeham/Twitter-like-website, pull requests merged in 2019-03, with the labels that each got.

#166 #124 Fix Travis CI build failing problem
  .travis.yml
  Test.php
  assets/query.php
  tests/DataObjects.php
  tests/SampleTest.php
  tests/TestCases.php
Labels: Bug

#180 #164 Advertisement and adblocker detection
  pages/feed.php
  pages/profile.php
  repeated/header.php
  resources/images/ads/R4VmGdsr_400x400.jpg
  resources/images/ads/adopt.jpg
  resources/images/ads/advertisingduck.png
  resources/images/ads/disneyland.jpg
  resources/images/ads/duck-dodgers.jpg
  resources/images/ads/duck-duck-goose.jpg
  resources/images/ads/ducktales.jpg
  resources/images/ads/fancyduck.jpg
  resources/images/ads/howard-the-duck.jpg
  resources/images/ads/lucky-duck.jpg
  resources/images/ads/oil.jpg
  resources/images/ads/trumpyducky.jpg
  resources/js/adsbygoogle.js
  resources/js/custom.js
Labels: Backend, Frontend

#205 #164 More ads
  pages/feed.php
  resources/images/ads/12princesses.jpg
  resources/images/ads/captainquack.jpg
  resources/images/ads/daredevil.jpg
  resources/images/ads/daredevilduck.jpg
  resources/images/ads/darkwing.jpg
  resources/images/ads/darkwing.png
  resources/images/ads/darkwing2.jpg
  resources/images/ads/deadpool.jpg
  resources/images/ads/doctorduck.jpg
  resources/images/ads/duck-and-goose.jpg
  resources/images/ads/duck-avenger.jpg
  resources/images/ads/duck-avengers.jpg
  resources/images/ads/duckavenger.jpg
  resources/images/ads/farmer.jpg
  resources/images/ads/fixitduck.jpg
  resources/images/ads/henry.jpg
  resources/images/ads/heyduck.jpg
  resources/images/ads/howard-the-duck2.jpg
  resources/images/ads/jewels.jpg
  resources/images/ads/lilquack.jpg
  resources/images/ads/noel.jpg
  resources/images/ads/parenting.jpg
  resources/images/ads/president.jpg
  resources/images/ads/psycho.jpg
  resources/images/ads/seafood.jpg
  resources/images/ads/shotgun.jpg
  resources/images/ads/slowdeath.jpg
  resources/images/ads/super patos.jpg
  resources/images/ads/super-patos.jpg
  resources/images/ads/trumpyducky.jpg
  resources/images/ads/worry.jpg
Labels: enhancement
